name: Quality Gates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint # Uses the 'lint' script from your package.json

      - name: Formatting Check (Prettier)
        run: npm run prettier:check # Uses the 'prettier:check' script

      - name: Unit Tests
        run: npm run test:ci # Uses the 'test:ci' script

      - name: Display Name
        run: echo "YourName_______!!!" # Replace YourName with your actual name

      - name: Build Project
        run: npm run build -- --prod

      - name: Create Artifact
        run: zip -r build-artifact.zip dist/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.zip
